version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - "MBXAI_MCP_WEATHER_EXAMPLE_NAME=MBXAI Mcp Weather Example"
      - "MBXAI_MCP_WEATHER_EXAMPLE_LOG_LEVEL=20"
      - "MBXAI_MCP_WEATHER_EXAMPLE_OPENROUTER_API_KEY=${OPENROUTER_API_KEY}"
      - "MBXAI_MCP_WEATHER_EXAMPLE_OPENROUTER_BASE_URL=https://openrouter.ai/api/v1"
    volumes:
      - ./src:/app/src
    restart: unless-stopped
